### PR TITLE
Add support for range events in the timeline chart

### PR DESCRIPTION
**Pull request by ankusht-work**
Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — CHANGES_REQUESTED** [review]
1- the patch is in for opacity
2- please add some examples in the index.ts like the arrows and symbols in the timeline chart.

**Comment by ankusht-work** [comment]
> Done

**Review by MatthewKhouzam — COMMENTED** [review]
image
I think the annotation is drawn several times... check out the opacity. Also, look at how the top and bottom half of the highlighted row are different.

**Comment by MatthewKhouzam** [comment]
https://user-images.githubusercontent.com/419535/118017032-1bb56780-b324-11eb-86b6-145ebf3affb7.mp4
The markers fail at zooming. :(

**Comment by ankusht-work** [comment]
> image
> I think the annotation is drawn several times... check out the opacity. Also, look at how the top and bottom half of the highlighted row are different.

Thank you for pointing this out. By adding lost event as a new layer to the timeline-chart, it does seem to fix all the issues.

**Comment by ankusht-work** [comment]
> https://user-images.githubusercontent.com/419535/118017032-1bb56780-b324-11eb-86b6-145ebf3affb7.mp4
> The markers fail at zooming. :(


lost_event

**Comment by MatthewKhouzam** [comment]
Double drawn when inited.
vokoscreen-2021-05-21_13-55-54

**Comment by ankusht-work** [comment]
> Double drawn when inited.
> vokoscreen-2021-05-21_13-55-54

Ok, I see what's going on here. In the time-graph-layer class, the addChild method directly calls the "render" instead of calling the update function and hence the double draw. The update method first clears the display object and then renders it.

**Review by bhufmann — APPROVED** [review]
Looks good to me!

**Pull request merged**
