### PR TITLE
Press esc to cancel mouse zooming

### PR DESCRIPTION
**Pull request by muddana-satish**
Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
No Objections

**Comment by bhufmann** [comment]
@muddana-satish  when is this needed?  Any steps to reproduce.
Is this to cancel a long lasting zoom operation 
or 
is there a case where the mouseZooming flag is not reset and pressing esc fixes this condition. If yes then we should figure out why the flag is not reset
or 
any other reasons?

Please let me know.

**Comment by muddana-satish** [comment]
> @muddana-satish when is this needed? Any steps to reproduce.

This is just a UX feature. If the user wants to zoom in by right click drag and then for some reason decides to cancel the zooming, there is no way he can do it. Pressing `esc` can takes him out of the zooming mode. 

In the screencast below, I cancelled zooming mode by pressing `esc`.
Kapture 2021-07-06 at 11 04 34

**Comment by bhufmann** [comment]
> > @muddana-satish when is this needed? Any steps to reproduce.
> 
> This is just a UX feature. If the user wants to zoom in by right click drag and then for some reason decides to cancel the zooming, there is no way he can do it. Pressing `esc` can takes him out of the zooming mode.
> 
> In the screencast below, I cancelled zooming mode by pressing `esc`.

Thanks for the information. Makes sense. Could you please add a sentence to the documentation (under the doc directory) to explain that behaviour? There is a description of the right click drag and it would fit there.

**Review by bhufmann — CHANGES_REQUESTED** [review]
Please add a line in the documentation for that:
https://github.com/theia-ide/timeline-chart/blob/master/doc/documentation.md

**Comment by muddana-satish** [comment]
> Please add a line in the documentation for that:
> https://github.com/theia-ide/timeline-chart/blob/master/doc/documentation.md

Update the documentation.

**Review by bhufmann — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
