### PR TITLE
Rename TimeGraphRowElement to TimeGraphStateComponent

### PR DESCRIPTION
**Pull request by PatrickTasse**
Also rename related classes, methods and variables.

Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
LGTM

**Comment by MatthewKhouzam** [comment]
Question, when we merge XY charts into this... will it still apply?

**Review by bhufmann — APPROVED** [review]
Looks good to me.

**Comment by PatrickTasse** [comment]
> Question, when we merge XY charts into this... will it still apply?

Those line graphs in a row would not be states, they would be something new, perhaps with the same parent class as the states.

**Comment by MatthewKhouzam** [comment]
Approved!

**Pull request merged**
