### PR TITLE
Adjust State's label Position based on view range

### LINKED ISSUE #68: State Labels should adjust based on the view range
Currently labels are aligned to center of the states.

Kapture 2020-10-23 at 14 11 17

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #68

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Comment by muddana-satish** [comment]
This is how it looks after changes while zooming in.

Kapture 2020-10-23 at 12 50 53

Sorry for the screen cast. I still haven't figured out how to use key-mon.

**Review by tahini — APPROVED** [review]
nice improvement, thanks

**Comment by muddana-satish** [comment]
Rebased after #60.

**Review by MatthewKhouzam — APPROVED** [review]
LGTM

**Pull request merged**
