### PR TITLE
Make all opacity levels work with PIXIjs 5.0

### PR DESCRIPTION
**Pull request by MatthewKhouzam**
Clamp values to range that is acceptable to PIXIjs 5

Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>

### CODE REVIEW

**Comment by muddana-satish** [comment]
We can remove changes from #57 if we're going with this PR.

**Review by tahini — APPROVED** [review]
Very nice, so when PIXI supports selecting 0 opacity states, we can easily change this, and this makes PR https://github.com/theia-ide/theia-trace-extension/pull/150 unnecessary. Me gusta!

**Comment by MatthewKhouzam** [comment]
@tahini the main reason is this is a PIXI issue. so I want to decouple it from our implementation. If we want to step away from that library it'll be easier.

**Comment by tahini** [comment]
@MatthewKhouzam Are you going to merge this? Or are you waiting for something?

**Comment by MatthewKhouzam** [comment]
Oops? :)

**Pull request merged**
