### PR TITLE
Change Event listeners from document to Canvas

### PR DESCRIPTION
**Pull request by muddana-satish**
Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Review by tahini — CHANGES_REQUESTED** [review]
I think the problem may be with the fact that the event listeners is added to the document, which, unless I'm mistaken, is the complete web page, and you make no verification of the active widget when you press the key.

For instance, if the focus is in the trace explorer on the left and we press up/down/left/right, both the trace explorer reacts to the key AND the selected state changes!!  I think you should add events to the react widgets that contain the view and add a e.stopPropagation() to the event once you process it.

**Comment by muddana-satish** [comment]
> I think the problem may be with the fact that the event listeners is added to the document, which, unless I'm mistaken, is the complete web page, and you make no verification of the active widget when you press the key.
> 
> For instance, if the focus is in the trace explorer on the left and we press up/down/left/right, both the trace explorer reacts to the key AND the selected state changes!! I think you should add events to the react widgets that contain the view and add a e.stopPropagation() to the event once you process it.

That was my initial thought. But the navigation works even after removing the focus from the chart in eclipse. Having eventlistener on document object ensures the same behavior in trace extension. (I did not want to change this).

**Comment by tahini** [comment]
> But the navigation works even after removing the focus from the chart in eclipse.

What do you mean here? From what I observe, it is true that we can zoom in/out (ctrl + mouse scroll) in the view even if the view is not focused, but the arrows (and key press in general) affect only the view that has focus.

**Comment by muddana-satish** [comment]
@tahini I pushed a commit based on your comments. Please review 0c48fbc8c3dcc491d0e402b835f08ed40b80ba72

**Review by tahini — CHANGES_REQUESTED** [review]
It works really great now! Could you rebase your branch on latest master, as this includes a patch by Avhinava that has been merged since. Also, could you please squash the commits and keep the commit message that best describes what this does now.

**Comment by muddana-satish** [comment]
> It works really great now! Could you rebase your branch on latest master, as this includes a patch by Avhinava that has been merged since. Also, could you please squash the commits and keep the commit message that best describes what this does now.

Squashed all the commits. Could you please verify it now.

**Review by tahini — APPROVED** [review]
Works beautfully! Thanks!

**Review by MatthewKhouzam — APPROVED** [review]
Great job decoupling it!

**Pull request merged**
