### PR TITLE
Horizontal Scroll moves timegraph chart in horizontal direction

### LINKED ISSUE #64: Ability to move the navigator using horizontal scroll
Users should be able to scroll the timegraph chart using horizontal scroll event.

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #64 

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Comment by muddana-satish** [comment]
It's more convenient to scroll using the mouse pad horizontally than to drag the navigator, using shift or shortcut keys.

Kapture 2020-10-21 at 16 39 49

**Review by tahini — COMMENTED** [review]
The patch looks generally good, seems to simplify the code.

Sorry for being a pain, but could you specify in the commit message, or the issue you mentioned, exactly which user actions are expected to do what here? What do you mean by 'Horizontal Scroll' and where the shift key fits in.

Also, in commit messages, you can just put 'fixes #64' to automatically close the issue once the PR is merged.

**Comment by tahini** [comment]
> It's more convenient to scroll using the mouse pad horizontally than to drag the navigator, using shift or shortcut keys.
> 
> Kapture 2020-10-21 at 16 39 49

In your screen casts, you can use the 'key-mon' utility to show the mouse and key presses, so that we see what user actions you were doing when recording the screencast. Here, we see there is scrolling happening, but the mouse pointer does not move, so we can't know how you made it move.

**Comment by muddana-satish** [comment]
> Sorry for being a pain, but could you specify in the commit message, or the issue you mentioned, exactly which user actions are expected to do what here? What do you mean by 'Horizontal Scroll' and where the shift key fits in.

Sorry for not being more descriptive. With this patch, user can use a two finger swipe horizontally on the keypad to move the timegraph chart in horizontal direction (this is irrelevant if you are using an external mouse as we cannot do a horizontal swipe using mouse). 

I believe this is more convenient than the current options(dragging the horizontal navigator, shift+mousewheel). All the shortcuts still work as usual. This is just an extra more convenient option in my opinion. What do you think?

I will update this information in the commit message.

> Also, in commit messages, you can just put 'fixes #64' to automatically close the issue once the PR is merged.

I already have this, right?

**Comment by tahini** [comment]
> > Sorry for being a pain, but could you specify in the commit message, or the issue you mentioned, exactly which user actions are expected to do what here? What do you mean by 'Horizontal Scroll' and where the shift key fits in.
> 
> Sorry for not being more descriptive. With this patch, user can use a two finger swipe horizontally on the keypad to move the timegraph chart in horizontal direction (this is irrelevant if you are using an external mouse as we cannot do a horizontal swipe using mouse).
> 
> I believe this is more convenient than the current options(dragging the horizontal navigator, shift+mousewheel). All the shortcuts still work as usual. This is just an extra more convenient option in my opinion. What do you think?
> 
> I will update this information in the commit message.

Ok, thanks for the precision

> 
> I already have this, right?

I don't know, it looks like it's part of the PR's conversation, but not in the commit message per se. We'll see when this PR closes, I guess.

**Review by tahini — APPROVED** [review]
I couldn't test the functionality as 2-finger scrolling is not working here in general, but everything else works as before and the code is nicer, so approved! Maybe @MatthewKhouzam can test the actual scrolling?

**Review by MatthewKhouzam — COMMENTED** [review]
Code is nice, I will now test it... 

Please use a full commit message like "Horizontal Scroll moves timegraph chart in horizontal direction"

then the description can be fixes 65.

consider we don't always have github available so scrolling through the logs can be an issue when you refer to a separate datasource.

**Comment by muddana-satish** [comment]
> I don't know, it looks like it's part of the PR's conversation, but not in the commit message per se. We'll see when this PR closes, I guess.

I always used it as part of the conversation and it closed all my linked issues.

**Comment by muddana-satish** [comment]
> Code is nice, I will now test it...
> 
> Please use a full commit message like "Horizontal Scroll moves timegraph chart in horizontal direction"
> 
> then the description can be fixes 65.
> 
> consider we don't always have github available so scrolling through the logs can be an issue when you refer to a separate datasource.

I don't know if I am doing something incorrectly. But my current log message is "Horizontal Scroll moves timegraph chart in horizontal direction". 

And 'fixes #65' is just for GitHub to link the issue (nothing to do with the log message). Isn't it correct?

**Review by MatthewKhouzam — COMMENTED** [review]
Code works and is perfect. Commit message needs to be updated.

**Review by MatthewKhouzam — COMMENTED** [review]
Here is the commit message:
-- copy here ---
Horizontal Scroll moves timegraph chart in horizontal direction

Fixes #65

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>
--- end copy ---

**Comment by tahini** [comment]
> And 'fixes #65' is just for GitHub to link the issue (nothing to do with the log message). Isn't it correct?

If it's not in the commit message, then we loose track of those fixes if we look at the git log. People don't usually go back to closed PRs, but later we may be bisecting or inspecting code and we'd like to be able to point to an issue from the git logs, if only to not bring back an issue when modifying code from a previous commit. So it's important to keep the issue id in the commit message too.

**Comment by muddana-satish** [comment]
Thanks @MatthewKhouzam  and @tahini for your suggestions. Points noted.

I updated the log message.

**Review by MatthewKhouzam — APPROVED** [review]

**Comment by MatthewKhouzam** [comment]
Looks great, thanks! next up: middle-click drag?

**Pull request merged**
