### PR TITLE
Set limit on zoom-in factor

### LINKED ISSUE #86: Browser freezes when zoom-in completely
Kapture 2020-12-24 at 12 38 29

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #86

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Comment by muddana-satish** [comment]
Doesn't allow the zoom once it reaches the limit. (In our case if the start and end are the same).

Kapture 2020-12-24 at 19 50 11

**Comment by mirsky** [comment]
Thanks for the patch, works well for mouse scroll and keyboard shortcuts.
Looks like it doesn't cover zooming-in by dragging the time axis though.

**Comment by muddana-satish** [comment]
> Thanks for the patch, works well for mouse scroll and keyboard shortcuts.
> Looks like it doesn't cover zooming-in by dragging the time axis though.

Thank you for pointing it out. Fixed it.

**Review by bhufmann — APPROVED** [review]
Thanks for the fix. No more frozen browser.

**Review by MatthewKhouzam — APPROVED** [review]

**Pull request merged**
