### PR TITLE
Resolves TypeError: Cannot read property viewRangeLength of undefined

### LINKED ISSUE #104: TypeError in TimeGraphChart
Appears to map to time-graph-chart.ts:190 : maybeFetchNewData()

Uncaught (in promise) TypeError: Cannot read property 'viewRangeLength' of undefined
    at TimeGraphChart.<anonymous> (:3000/45.bundle.js:1789)
    at step (:3000/45.bundle.js:1639)
    at Object.next (:3000/45.bundle.js:1620)
    at :3000/45.bundle.js:1614
    at new Promise (<anonymous>)
    at push.../../timeline-chart/timeline-chart/lib/layer/time-graph-chart.js.__awaiter (:3000/45.bundle.js:1610)
    at TimeGraphChart.push.../../timeline-chart/timeline-chart/lib/layer/time-graph-chart.js.TimeGraphChart.maybeFetchNewData (:3000/45.bundle.js:1784)
    at TimeGraphChart.push.../../timeline-chart/timeline-chart/lib/layer/time-graph-chart.js.TimeGraphChart.updateChart (:3000/45.bundle.js:1778)
    at TimegraphOutputComponent.componentDidUpdate (:3000/45.bundle.js:4503)

### PR DESCRIPTION
**Pull request by ankusht-work**
Fixes #104

Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>

### CODE REVIEW

**Comment by bhufmann** [comment]
@ankusht-work is this one ready for review?

**Comment by ankusht-work** [comment]
> @ankusht-work is this one ready for review?

No, it isn't ready yet. I still see errors in the theia-trace-extension. I will move this PR to draft.

**Comment by ankusht-work** [comment]
> @ankusht-work is this one ready for review?

This is ready for review now. It also fixes issue [203](https://github.com/theia-ide/theia-trace-extension/issues/203).

**Review by bhufmann — APPROVED** [review]
This PR fixes the error when using it in theia-trace-extension.

**Review by PatrickTasse — APPROVED** [review]

**Pull request merged**
